notifications:
  email: false

language: python

matrix:
  include:
    - services:
        - docker
      env: DOCKER_IMAGE=jashshah1401/pygnuastro:0.18-manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
    # - sudo: required
    #   services:
    #     - docker
    #   env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686
    #        PRE_CMD=linux32
    #        PLAT=manylinux2014_i686

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-wheels.sh
  - ls wheelhouse/