name: Build ManyLinux Wheels and SDist
on: [push]

jobs:
  manylinux-wheels:
    runs-on: ubuntu-latest
    container: 
      image: jashshah1401/pygnuastro:0.18-manylinux2014_x86_64
      env:
        PLAT: manylinux2014_x86_64
      volumes:
        - ${{ github.workspace }}:/io

    steps:
      - uses: actions/checkout@v3
      - name: Run Build Wheels Script in Container
        run: |
          cd /io
          chmod +x ./travis/build-wheels.sh
          ./travis/build-wheels.sh
        shell: bash
      - name: Upload ManyLinux Wheels
        uses: actions/upload-artifact@v3
        with:
          name: ManyLinux wheel
          path: /io/wheelhouse/

  sdist:
    name: Build source distribution (sdist)
    runs-on: [ubuntu-latest]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gnuastro
          dpkg -l | grep gnuastro
          sudo ldconfig
          python3 -m pip install --upgrade --disable-pip-version-check -r dev-requirements.txt
      - name: Build sdist
        run: |
          python3 setup.py --verbose build_ext
          python3 setup.py --verbose sdist
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Source distribution
          path: dist/

  macos_wheels:
    name: Build MacOS wheels
    # Note: the container MacOS version may differ from the SDK
    # used to build Python there.  It is the latter that determines
    # the wheel's platform tag.
    # https://github.com/actions/virtual-environments/tree/master/images/macos
    # https://github.com/MacPython/wiki/wiki/Spinning-wheels
    # https://github.com/actions/virtual-environments/issues/696
    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MacPorts
      run: |
        wget https://github.com/macports/macports-base/releases/download/v2.7.2/MacPorts-2.7.2-11-BigSur.pkg
        sudo installer -pkg ./MacPorts-2.7.2-11-BigSur.pkg -target /
    - name: Install dependencies
      run: |
        pkgutil --pkgs
        sudo port selfupdate
        sudo port install gnuastro
        python -m pip install --upgrade --disable-pip-version-check -r dev-requirements.txt
        python -m pip install --upgrade --disable-pip-version-check delocate
    - name: Build wheels
      run: |
        python setup.py --quiet bdist_wheel -d wheels/
    - name: Repair wheels
      run: |
        delocate-listdeps --all ./wheels/*.whl
        delocate-wheel -w wheelhouse -v ./wheels/*.whl
    - uses: actions/upload-artifact@v3
      with:
        name: MacOS cp${{ matrix.python-version }} wheel
        path: wheelhouse/